name: thirdProject-check

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: make install

      - name: Run Linter
        run: make lint